# Netlify configuration for Django static files
# Note: This will only serve static files, not the Django backend
# For full Django deployment, use Railway, Heroku, or Render

[build]
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.11.4"

# Redirect all requests to index.html for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200